#https://www.rosehosting.com/blog/how-to-install-redmine-on-ubuntu-18-04/
---
- name: System | Add needed apt keys
  become: yes
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 561F9B9CAC40B2F7

- name: System | Add needed repositories
  become: yes
  apt_repository:
    repo: deb https://oss-binaries.phusionpassenger.com/apt/passenger bionic main
    state: present

- name: System | apt-get update
  become: yes
  apt: 
    update_cache: yes

- name: System | Install common packages
  become: yes
  apt:
    state: present
    name:
      - apt-transport-https
      - autoconf
      - build-essential
      - ca-certificates
      - dirmngr
      - gnupg
      - imagemagick
      - libcurl4-openssl-dev 
      - libncurses5-dev #!
      - libffi-dev #!
      - libgdbm5 #!
      - libgdbm-dev #!
      - libmagickcore-dev #!
      - libmagickwand-dev
      - libmysqlclient-dev
      - libnginx-mod-http-passenger
      - libreadline6-dev #!
      - libreadline-dev #!
      - libssl-dev #!
      - libyaml-dev #!
      - mysql-server
      - nginx
      - passenger
      - python-pip
      - python-mysqldb
      - python3-pip 
      - python3-mysqldb
      - unzip
      - zlib1g-dev #!

- name: System | Install pymysql
  become: yes
  shell: python3 -m pip install PyMySQL