#https://www.rosehosting.com/blog/how-to-install-redmine-on-ubuntu-18-04/
---
# - name: System | Add needed apt keys
#   become: yes
#   apt_key:
#     keyserver: hkp://keyserver.ubuntu.com:80
#     id: 561F9B9CAC40B2F7

# - name: System | Add needed repositories
#   become: yes
#   apt_repository:
#     repo: deb https://oss-binaries.phusionpassenger.com/apt/passenger bionic main
#     state: present

- name: System | apt-get update
  become: yes
  apt:
    update_cache: yes

- name: System | Install common packages
  become: yes
  apt:
    state: present
    name:
      - apt-transport-https
      - autoconf
      - build-essential
      - ca-certificates
      - dirmngr
      - gnupg
      - imagemagick
      - libcurl4-openssl-dev
      - libmagickwand-dev
      - libmysqlclient-dev
      #- libnginx-mod-http-passenger
      - mysql-server
      - nginx
      #- passenger
      - python3-pip
      - python3-mysqldb
      - unzip

- name: System | Install pymysql
  become: yes
  pip:
    name: PyMySQL
