---
- name: System | apt-get update
  become: yes
  apt:
    update_cache: yes

- name: System | Install common packages
  become: yes
  apt:
    state: present
    name:
      - apt-transport-https
      - autoconf
      - build-essential
      - ca-certificates
      - dirmngr
      - gnupg
      - imagemagick
      - libcurl4-openssl-dev
      - libmagickwand-dev
      - libmysqlclient-dev
      - mysql-server
      - nginx
      - python3-pip
      - python3-mysqldb
      - unzip

- name: System | Install pymysql
  become: yes
  pip:
    name: PyMySQL
