---
# Ansible Documentation says iptables has the parameter destination_ports,
# but it's failing for me. That's why i use destination_port
- name: Iptables | Allow connections on multiple ports
  become: yes
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
  with_items: 
    - "22"
    - "80"

- name: Iptables | Set the policy for the INPUT chain to DROP
  become: yes
  iptables:
    chain: INPUT
    policy: DROP