---
- name: Iptables | Allow related and established connections
  become: yes
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED

- name: Iptables | Allow new connections
  become: yes
  iptables:
    chain: INPUT
    action: append
    cstate: NEW
    destination_port: "{{ item }}"
    jump: ACCEPT
  with_items:
    - "22"
    - "80"
    - "443"

- name: Iptables | Allow loopback
  become: yes
  iptables:
    action: append
    in_interface: lo
    chain: INPUT
    jump: ACCEPT

- name: Iptables | Set the policy for the INPUT chain to DROP
  become: yes
  iptables:
    chain: INPUT
    policy: DROP

- name: Iptables | Set the policy for the OUTPUT chain to ALLOW
  become: yes
  iptables:
    chain: OUTPUT
    policy: ALLOW
