---
- name: Iptables | Allow connections on multiple ports
  become: yes
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
  with_items: 
    - "22"
    - "80"
    - "443"

- name: Iptables | Set the policy for the INPUT chain to DROP
  become: yes
  iptables:
    chain: INPUT
    policy: DROP