---
- name: MySQL | Create Redmine Database
  mysql_db: 
    name: redmine
    login_user: root 
    login_password: "{{ root_db_pass }}" 
    encoding: UTF8 

- name: MySQL | Create Redmine DB User
  mysql_user: 
    name: "{{ redmine_db_user }}" 
    password: "{{ redmine_db_pass }}" 
    login_user: root 
    login_password: "{{ root_db_pass }}"
    priv: "{{ redmine_db_name }}.*:ALL"