---
# prepare users and groups
- name: Redmine | Create redmine group
  become: yes
  group:
    name: redmine
    state: present

- name: Redmine | Create redmine user
  become: yes
  user:
    name: redmine
    shell: /bin/bash
    group: redmine
    groups: redmine
    state: present

- name: Redmine | Create redmine_admin group
  become: yes
  group:
    name: redmine_admin
    state: present

- name: Redmine | Create redmine_admin user
  become: yes
  user:
    name: redmine_admin
    shell: /bin/bash
    group: redmine
    groups: redmine,redmine_admin
    state: present

- name: Redmine | Passwordless sudo to redmine_admin
  become: yes
  lineinfile: "dest=/etc/sudoers state=present
    regexp='^redmine_admin ALL= NOPASSWD'
    line='redmine_admin ALL= NOPASSWD: ALL'"

- name: Redmine | Set up /home for redmine user
  become: yes
  become_user: redmine_admin
  file:
    owner: redmine
    dest: /home/redmine
    mode: 775
    state: directory
    recurse: yes

- name: Redmine | Install Ruby
  become: yes
  become_user: redmine_admin
  apt: pkg=ruby-full

- name: Redmine | Install Ruby Bundler
  become: yes
  become_user: redmine_admin
  community.general.gem:
    name: bundler
    state: present

- include: redmine.yml
  become_user: redmine
