---
- name: Redmine | Create user that will use redmine
  become: yes
  user:
    name: "{{ redmine_user }}"
    shell: /bin/bash

- name: Redmine | Check whether Redmine version "{{ redmine_version }}" is already downloaded
  stat:
    path: "{{ redmine_path }}/redmine-{{ redmine_version }}"
  register: redmine_directory

# Setup ruby
- include: setup_ruby.yml
  when: not redmine_directory.stat.exists

# Download Redmine version "{{ redmine_version }}"
- include: redmine.yml
  when: not redmine_directory.stat.exists

# Install ruby dependencies on redmine
- include: install_deps.yml
  #when: not redmine_directory.stat.exists

- include: puma.yml

# Change owner to redmine user so it can be used by nginx
# - name: Redmine | Change owner to "{{ redmine_rvm_user }}"
#   become: yes
#   file:
#     dest: "{{ redmine_path }}/redmine-{{ redmine_version }}"
#     owner: "{{ redmine_user }}"
#     group: redmine
#     recurse: yes
#   when: not redmine_directory.stat.exists
