---
# prepare users and groups
- name: Redmine | Create redmine group
  become: yes
  group:
    name: redmine
    state: present

- name: Redmine | Create redmine user
  become: yes
  user:
    name: redmine
    shell: /bin/bash
    group: redmine
    groups: redmine
    state: present

- name: Redmine | Create redmine_admin group
  become: yes
  group:
    name: redmine_admin
    state: present

- name: Redmine | Create redmine_admin user
  become: yes
  user:
    name: redmine_admin
    shell: /bin/bash
    group: redmine
    groups: redmine,redmine_admin
    state: present

- name: Redmine | Passwordless sudo to redmine_admin
  become: yes
  lineinfile: "dest=/etc/sudoers state=present
    regexp='^redmine_admin ALL= NOPASSWD'
    line='redmine_admin ALL= NOPASSWD: ALL'"

- name: Redmine | Set up /home for redmine user
  become: yes
  file:
    owner: redmine
    group: redmine
    path: "/home/redmine"
    mode: 775
    state: directory
    recurse: yes

- name: Redmine | Install Ruby
  become: yes
  become_user: redmine_admin
  apt: pkg=ruby-full

- name: Redmine | Install Ruby Bundler
  #become: yes
  #become_user: redmine #_admin
  community.general.gem:
    name: bundler
    state: present
    #install_dir: /home/redmine
    user_install: no

#- include: redmine.yml

- name: Redmine | Download source code
  become_user: redmine
  get_url:
    url: "{{ redmine_url }}/redmine-{{ redmine_version }}.zip"
    dest: /tmp/redmine.zip

- name: Redmine | Delete destination folder
  become: yes
  #become_user: redmine #_admin
  file:
    state: absent
    path: "{{ redmine_path }}/redmine-{{ redmine_version }}"

- name: Redmine | Extract
  become: yes
  #become_user: redmine_admin
  #shell: unzip /tmp/redmine.zip -d "{{ redmine_path }}"
  unarchive:
    src: /tmp/redmine.zip
    dest: "{{ redmine_path }}"
    owner: redmine
    group: redmine


- name: Redmine | Set up redmine path for redmine user
  become: yes
  file:
    owner: redmine
    group: redmine
    path: "{{ redmine_path }}/redmine-{{ redmine_version }}"
    #mode: 775
    state: directory
    recurse: yes

- name: Redmine | Install Dependencies
  #become: yes
  become_user: redmine #_admin
  shell: bundle install 
  args:
    chdir: "{{ redmine_path }}/redmine-{{ redmine_version }}"
  #bundler: 



- name: Redmine | Copy DB configuration
  become_user: redmine
  template:
    src: database.yml.j2
    dest: "{{ redmine_path }}/redmine-{{ redmine_version }}/config/database.yml"
    mode: 0644

- name: Redmine | Copy Configuration
  become_user: redmine
  template:
    src: configuration.yml.j2
    dest: "{{ redmine_path }}/redmine-{{ redmine_version }}/config/configuration.yml"
    mode: 0644

- name: Redmine | Install mysql2 gem
  become_user: redmine
  community.general.gem:
    name: mysql2
    state: latest

- name: Redmine | Generate secret token
  become_user: redmine
  shell: bundler exec rake generate_secret_token
  args:
    chdir: "{{ redmine_path }}/redmine-{{ redmine_version }}"

- name: Redmine | Migrate DB
  become_user: redmine
  shell: RAILS_ENV=production bundle exec rake db:migrate
  args:
    chdir: "{{ redmine_path }}/redmine-{{ redmine_version }}"

- name: Redmine | Generate default config
  become_user: redmine
  shell: bundle exec rake redmine:load_default_data RAILS_ENV=production REDMINE_LANG=en
  args:
    chdir: "{{ redmine_path }}/redmine-{{ redmine_version }}"

