---
- name: Redmine | Install Puma
  become_user: "{{ redmine_rvm_user }}"
  become: yes
  shell: "rvm-exec {{ redmine_rvm_ruby_version }} gem install puma"
  args:
    chdir: "{{ redmine_path }}/redmine-{{ redmine_version }}"
  environment:
    PATH: "{{ redmine_rvm_path }}:{{ ansible_env.PATH }}"

- name: Redmine | Set Puma service
  become: yes
  template:
    src: puma.service.j2
    dest: "/etc/systemd/system/puma.service"
    force: yes
    owner: "{{ redmine_rvm_user }}"
    mode: 0644
  notify: Redmine | Restart Puma

- name: Redmine | Config Puma
  become_user: "{{ redmine_rvm_user }}"
  become: yes
  template:
    src: puma.rb.j2
    dest: "{{ redmine_path }}/redmine-{{ redmine_version }}/config/puma.rb"
    mode: 0644
  notify: Redmine | Restart Puma

- name: Redmine | Start Puma
  become: yes
  service:
    name: puma
    state: started
    enabled: yes