---
- name: Redmine | Download source code
  become_user: redmine
  get_url:
    url: "{{ redmine_url }}/redmine-{{ redmine_version }}.zip"
    dest: /tmp/redmine.zip

- name: Redmine | Delete destination folder
  become: yes
  file:
    state: absent
    path: "{{ redmine_path }}/redmine-{{ redmine_version }}"

# - name: Redmine | Create destination folder
#   become: yes
#   file:
#     owner: redmine
#     state: directory
#     path: "{{ redmine_path }}/redmine-{{ redmine_version }}"
#     mode: 2775

- name: Redmine | Extract
  become: yes
  #become_user: redmine
  shell: unzip /tmp/redmine.zip -d "{{ redmine_path }}"

- name: Redmine | Change owner
  become: yes
  file: 
    owner: redmine
    dest: "{{ redmine_path }}/redmine-{{ redmine_version }}"
    mode: 775
    state: directory
    recurse: yes

- name: Redmine | Install Dependencies
  become_user: redmine
  shell: bundle install
  args:
    chdir: "{{ redmine_path }}/redmine-{{ redmine_version }}"

- name: Redmine | Copy DB configuration
  become_user: redmine
  template:
    src: database.yml.j2
    dest: "{{ redmine_path }}/redmine-{{ redmine_version }}/config/database.yml"
    mode: 0644

- name: Redmine | Copy Configuration
  become_user: redmine
  template:
    src: configuration.yml.j2
    dest: "{{ redmine_path }}/redmine-{{ redmine_version }}/config/configuration.yml"
    mode: 0644

- name: Redmine | Install mysql2 gem
  become_user: redmine
  community.general.gem:
    name: mysql2
    state: latest

- name: Redmine | Generate secret token
  become_user: redmine
  shell: bundler exec rake generate_secret_token
  args:
    chdir: "{{ redmine_path }}/redmine-{{ redmine_version }}"

- name: Redmine | Migrate DB
  become_user: redmine
  shell: RAILS_ENV=production bundle exec rake db:migrate
  args:
    chdir: "{{ redmine_path }}/redmine-{{ redmine_version }}"

- name: Redmine | Generate default config
  become_user: redmine
  shell: bundle exec rake redmine:load_default_data RAILS_ENV=production REDMINE_LANG=en
  args:
    chdir: "{{ redmine_path }}/redmine-{{ redmine_version }}"
