---
- name: Redmine | Download source code
  get_url:
    url: "{{ redmine_url }}/redmine-{{ redmine_version }}.zip"
    dest: /tmp/redmine.zip

- name: Redmine | Delete destination folder
  file:
    state: absent
    path: "{{ redmine_path }}/redmine-{{ redmine_version }}"

- name: Redmine | Extract
  shell: unzip /tmp/redmine.zip -d "{{ redmine_path }}"

- name: Redmine | Install Dependencies
  shell: bundle install
  args:
    chdir: "{{ redmine_path }}/redmine-{{ redmine_version }}"

- name: Redmine | Copy DB configuration
  template:
    src: database.yml.j2
    dest: "{{ redmine_path }}/redmine-{{ redmine_version }}/config/database.yml"
    mode: 0644

- name: Redmine | Copy Configuration
  template:
    src: configuration.yml.j2
    dest: "{{ redmine_path }}/redmine-{{ redmine_version }}/config/configuration.yml"
    mode: 0644

- name: Redmine | Install mysql2 gem
  community.general.gem:
    name: mysql2
    state: latest

- name: Redmine | Generate secret token
  shell: bundler exec rake generate_secret_token
  args:
    chdir: "{{ redmine_path }}/redmine-{{ redmine_version }}"

- name: Redmine | Migrate DB
  shell: RAILS_ENV=production bundle exec rake db:migrate
  args:
    chdir: "{{ redmine_path }}/redmine-{{ redmine_version }}"

- name: Redmine | Generate default config
  shell: bundle exec rake redmine:load_default_data RAILS_ENV=production REDMINE_LANG=en
  args:
    chdir: "{{ redmine_path }}/redmine-{{ redmine_version }}"
