- name: Ngnix | Disable default site
  become: yes
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent

- name: Nginx | Configuration
  become: yes
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ nginx_redmine_url }}.conf"
    mode: 0644

- name: Nginx | Symbolic Link
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ nginx_redmine_url }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ nginx_redmine_url }}.conf"
    state: link
  notify: Nginx | Restart
  
- name: Ngnix | Add the user www-data to {{ redmine_rvm_user }} group
  become: yes
  user:
    name: www-data
    shell: /bin/bash
    groups:
      - "{{ redmine_rvm_user }}"
    append: yes