- name: Ngnix | Disable default site
  become: yes
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent

- name: Nginx | Configuration
  become: yes
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ nginx_redmine_url }}.conf"

- name: Nginx | Symbolic Link
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ nginx_redmine_url }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ nginx_redmine_url }}.conf"
    state: link

- name: Nginx | Restart
  become: yes
  service:
    name: nginx
    state: restarted
    enabled: yes
