---
- name: Deploy Redmine
  hosts: all
  roles:
    - common
    - role: db
      when: use_externalDB == "false"
    - role: externalDB
      when: use_externalDB == "true"
    - redmine
    - nginx
    - iptables
  vars_files:
    - vars/all.yml
